### ISSUE TITLE
Some problems about inference

### ISSUE THREAD

**Issue by linjikun1** [AISE-TUDelft/Capybara-BinT5#11]
**I have downloaded the DecomC counterpart of model and completed the replacement. My problems are as follows:**

1. How do I localize the deployment model for inference tasks? I noticed that it differs from the codet5-base model only in the pytorch_model.bin file. Does it mean that the steps I take to deploy the model are similar to codet5-base model?

2. I noticed that your dataset is formatted as shown below.

![image](https://github.com/user-attachments/assets/58e8d62f-57e8-4e83-89ed-18be39329dec)

Assuming I now have a piece of DecomC code, do I need to convert the format before letting the model do the inference?

3. I want to determine what the inputs and outputs of the model are when I'm trying to inference? Is the input supposed to be disassembled code in a specific format (assuming I want to use the DecomC counterpart of the model)? And would the output be a paragraph of summary?

**Sincerely look forward to your guidance.**

**Comment by aalkaswan** [comment]
Hi,

Sorry for the late response.

1. Yes deployment should be the same 
2. Yes this is the format used by CodeT5 and CodeXGlue. So if you use the code from the CodeT5 repo to run the model, you don't need to do anything. If you're using the model from HF and loading in the data without that framework, you only need to do ' '.join(list) to turn it into a single string.
3. Yes that is right, it turns a function (source code, decompiled code, etc.) into a summary. The length of the summary is usually around 1 sentence

Let me know if you need anything else

**Comment by linjikun1** [comment]
Hi,

When I only left the `-- do test` parameter [here](https://github.com/salesforce/CodeT5/blob/e78a61a17f6dc2f3cbb968447d3e2d065b426e7b/CodeT5/sh/exp_with_args.sh#L87) for direct model inference, an error was reported indicating that **the checkpoint file was missing in the directory below**,

`CodeT5/CodeT5/sh/saved_models/summarize/decomC/codet5_base_all_lr5_bs48_src256_trg128_pat2_e15/checkpoint-best-bleu/`

I guess it's because I didn't train beforehand. The code works when I copy pytorch_model.bin under `model/codet5-base/` into the above directory.

My problems are below:

1. Is there a difference between pytorch_model.bin file and checkpoint file in model inference? What roles do they play respectively in the process of model inference?

2. Is it correct that I copy pytorch_model.bin directly to the above directory as a checkpoint file? Or do I have to train again to get the best checkpoint file?

**Comment by aalkaswan** [comment]
Hi,

They should be the same file, the CodeT5 trainer keeps a copy of the best-performing model in that folder. Yes, it is correct that you copied it to that folder.

Let me know if you have any more questions
