### ISSUE TITLE
Issues With Setup Steps

### ISSUE THREAD

**Issue by wtegge2** [AISE-TUDelft/Capybara-BinT5#7]
I was following your setup steps, and I ran into several issues. The first issue is that the curl commands to obtain both the data and pretrained checkpoints do not work. I have shown an example of what happens in an image included. I was able to obtain the Capybara.zip by using “wget” instead of curl. 
 
![image_of_curl_error](https://github.com/AISE-TUDelft/Capybara-BinT5/assets/80014792/dd1243d7-b039-499a-8ce2-b67a83c6e4a1)

The second issue is that the BinT5 checkpoints are unattainable. The link provided is the same as the one for the data. I am not sure if this is intentional or not. When I follow that link, it only downloads the Capybara.zip and not the BinT5.zip. How can I get to the BinT5.zip checkpoints? 

The last issue is that the command to setup the data folders (mkdir -p CodeT5\data\summarize\{C,decomC,demiStripped,strippedDecomC}) is not working as intended. I am assuming it is supposed to create 4 separate folders: C, decomC, demiStripped, strippedDecomC. Instead, it creates one folder named “CodeT5datasummarize{C,decomC,demiStripped,strippedDecomC}”. 

The primary issue I would like help with and/or a solution to is getting the BinT5.zip file with the checkpoints.

**Comment by aalkaswan** [comment]
Thanks for reaching out, 

Here is the download link to the BinT5 checkpoints: https://zenodo.org/records/7229913/files/BinT5.zip?download=1
The Zenodo page also has some download instructions: https://zenodo.org/records/7229913

I'll look into the other issues and update the repo, please let me know if you run into any other issues 🙂
